import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  const AppLocalizations(this.locale);

  static const supportedLocales = [Locale('en'), Locale('ar')];

  static const _values = <String, Map<String, String>>{
    'en': {
      'appName': 'Naraak',
      'primaryHealthcarePortal': 'Primary Healthcare Portal',
      'signIn': 'Sign in',
      'enterCprNumber': 'Enter your CPR number to continue',
      'cprNumber': 'CPR NUMBER',
      'cprDigitsOnly': 'CPR number must contain digits only',
      'cprTooShort': 'CPR number looks too short',
      'loginDemo': 'Log in with eKey (Demo)',
      'home': 'Home',
      'homeTab': 'Home',
      'services': 'Services',
      'servicesTab': 'Services',
      'appointments': 'Appointments',
      'appointmentsTab': 'Appointments',
      'profile': 'Profile',
      'profileTab': 'Profile',
      'welcome': 'Welcome back',
      'healthCenter': 'My health center',
      'upcoming': 'Upcoming appointment',
      'notifications': 'Notifications',
      'higherPriority': 'Quick access',
      'moreServices': 'More services',
      'settings': 'Settings',
      'darkMode': 'Dark mode',
      'arabic': 'العربية',
      'english': 'English',
      'language': 'Language',
      'decreaseTextSize': 'Decrease text size',
      'increaseTextSize': 'Increase text size',
      'welcomeHeadline': 'Primary Healthcare, Closer to You',
      'welcomeSubtitle':
          'All your PHC services in one place. Fast. Easy. Secure.',
      'fast': 'Fast',
      'secure': 'Secure',
      'easy': 'Easy',
      'loginWithEkey': 'Login with eKey',
      'learnMoreNaraak': 'Learn more about Naraak',
      'naraakPrototypeDescription':
          'Naraak is a prototype digital e-services platform for Bahrain Primary Healthcare Centers.',
      'back': 'Back',
      'welcomeToNaraak': 'Welcome to Naraak',
      'useCprSecurely': 'Use your CPR number to continue securely.',
      'ekeyAuthentication': 'eKey Authentication',
      'simulatedAccess': 'Simulated prototype access',
      'cprNumberLabel': 'CPR Number',
      'enterNineDigitCpr': 'Enter your 9-digit CPR',
      'enterCprNumberValidation': 'Enter your CPR number',
      'cprMustBeNineDigits': 'CPR number must contain 9 digits',
      'continueWithEkey': 'Continue with eKey',
      'completeYourProfile': 'Complete Your Profile',
      'tellUsAboutYourself': 'Tell us about yourself',
      'profileSetupSubtitle':
          'A few details to personalize your dashboard. This data stays on your device for this demo session only.',
      'cprFromLogin': 'CPR Number (from login)',
      'fullName': 'Full Name',
      'enterFullName': 'Enter your full name',
      'enterValidAge': 'Enter a valid age',
      'mustBeFifteen': 'Must be 15 or older',
      'female': 'Female',
      'male': 'Male',
      'mobileNumber': 'Mobile Number',
      'enterMobileNumber': 'Enter your mobile number',
      'assignedHealthCenter': 'Assigned Health Center',
      'saveAndContinue': 'Save & Continue',
      'hooraHealthCenter': 'Hoora Health Center',
      'naimHealthCenter': 'Naim Health Center',
      'muharraqHealthCenter': 'Muharraq Health Center',
      'biladQadeemHealthCenter': 'Bilad Al-Qadeem Health Center',
      'yousifHealthCenter': 'Yousif HC (Sitra)',
      'dashboardLoadError': 'We could not load your dashboard',
      'pleaseTryAgain': 'Please try again.',
      'tryAgain': 'Try Again',
      'upcomingAppointment': 'Upcoming Appointment',
      'viewAllAppointments': 'View all appointments',
      'topServices': 'Top Services',
      'viewAllServices': 'View all services',
      'webHeroTitle': 'Primary Healthcare,\nCloser to You',
      'webHeroSubtitle':
          'All your primary healthcare services in one place.\nFast. Easy. Secure.',
      'dashboardSearchHint': 'Search for services, health centers and more...',
      'secureTrusted': 'Secure & Trusted',
      'allDayAccess': '24/7 Access',
      'forYourFamily': 'For You & Your Family',
      'betterHealthEveryday': 'Better Health, Everyday',
      'noUpcomingAppointment': 'No upcoming appointment',
      'bookWhenReady': 'Book an appointment when you are ready.',
      'generalPractitioner': 'General Practitioner',
      'type': 'Type',
      'inCenter': 'In-center',
      'viewDetails': 'View Details',
      'yourFamilyDoctor': 'Your Family Doctor',
      'notAssigned': 'Not assigned',
      'familyMedicine': 'Family Medicine',
      'viewDoctor': 'View Doctor',
      'bookingServiceSubtitle': 'In-center & tele-appointment',
      'mammogramScreening': 'Mammogram Screening',
      'mammogramSubtitle': 'Early detection saves lives',
      'vaccinationRecords': 'Vaccination Records',
      'vaccinationSubtitle': 'View and download certificates',
      'medicalReportsSubtitle': 'Request and download reports',
      'hajjCertificate': 'Electronic Hajj Certificate',
      'applyAndDownload': 'Apply and download',
      'newbornSehatiCard': 'Newborn Sehati Card',
      'newbornSubtitle': 'Apply for your newborn',
      'updateAddress': 'Update Address',
      'updateAddressSubtitle': 'Update your assigned center',
      'healthFeeExemption': 'Health Fee Exemption',
      'feeExemptionSubtitle': 'Apply for exemption',
      'changeFamilyDoctor': 'Change Family Doctor',
      'changeDoctorSubtitle': 'Choose your family doctor',
      'mobileUnitService': 'Mobile Unit Service',
      'mobileUnitSubtitle': 'Healthcare at your doorstep',
      'phcResearch': 'PHC Research',
      'phcResearchSubtitle': 'Research projects and studies',
      'healthcareAtFingertips': 'Healthcare at\nYour Fingertips',
      'appPromoDescription':
          'Book appointments, access your records, track requests, receive reminders and manage your healthcare anywhere.',
      'openNaraakApp': 'Open Naraak App',
      'availablePrototypeApp': 'Available as the Naraak prototype app',
      'healthTip': 'Health Tip',
      'healthTipBody':
          'Drink plenty of water, eat balanced meals, and get enough sleep. Small daily habits lead to a healthier you.',
      'toggleDarkMode': 'Toggle dark mode',
      'readScreenAloud': 'Read screen aloud',
      'screenReaderAnnouncement': 'Screen reader activated for this demo.',
      'screenReaderDemo': 'Screen reader announced (demo).',
      'logout': 'Log out',
      'externalApiTitle': 'External API required',
      'externalApiMessage':
          'This service requires an external API to operate. The interface is ready, but connect the service API to enable live requests.',
      'close': 'Close',
      'startService': 'Start Service',
      'guest': 'Guest',
      'notSet': 'Not set',
      'cpr': 'CPR',
      'booking': 'Booking Appointments',
      'medicalReports': 'Medical Reports & Certificates',
      'teleAppointment': 'Tele-Appointment Instructions',
      'changeDoctor': 'Change Family Doctor',
      'addressUpdate': 'Update Residential Address',
      'vaccinations': 'Vaccination Records & Certificate',
      'hajj': 'Electronic Hajj Certificate',
      'feeExemption': 'Health Fee Exemption Card',
      'mobileUnit': 'Request Mobile Unit Service',
      'mammogram': 'Mammogram Appointment Requests',
      'newborn': 'Sehati Card for Newborns',
      'research': 'PHC Research Applications',
      'catAppointments': 'Appointments & Consultation',
      'catRecords': 'My Records',
      'catAdmin': 'Administrative Services',
      'catResearch': 'Research Applications',
      'allServices': 'All Services',
      'yourCareTeam': 'Your care team',
      'yourAssignedFamilyDoctor': 'Your assigned family doctor',
      'nextAppointment': 'Next appointment',
      'yourUpcomingVisit': 'Your upcoming visit',
      'popularServices': 'Popular services',
      'startWithWhatYouNeedToday': 'Start with what you need today',
      'viewingAs': 'Viewing as',
      'quickAccess': 'Quick access',
      'commonServices': 'Common services',
      'bookAppointment': 'Book appointment',
      'medicalReportsQuick': 'Medical reports',
      'vaccinationsQuick': 'Vaccinations',
      'allServicesQuick': 'All services',
      'noUpcomingAppointments': 'No upcoming appointments',
      'tapToScheduleNewVisit': 'Tap to schedule a new visit',
      'pendingRequests': 'Pending requests',
      'keepTrackOfApplications': 'Keep track of applications and updates.',
      'noPendingRequests': 'No pending requests',
      'viewRequests': 'View requests',
      'privacyMatters': 'Your privacy matters',
      'privacyDescription':
          'Naraak keeps your health information safe and only uses it to provide your care.',
      'privacySecurity': 'Privacy & security',
      'yourNaraakProfile': 'YOUR NARAAK PROFILE',
      'profileSettingsTitle': 'Profile & settings',
      'profileSettingsSubtitle':
          'Manage your identity, preferences and family access.',
      'primaryMedicalTheme': 'PRIMARY MEDICAL THEME',
      'signOut': 'Sign Out',
      'personalInfoMenu': 'Personal Info & Blood Type',
      'securityMenu': 'Privacy & Security',
      'familyMenu': 'Family Members & Dependents',
      'appSettingsMenu': 'App Settings',
      'helpSupportMenu': 'Help & User Inquiries',
      'feedbackAndEvaluation': 'FEEDBACK & EVALUATION',
      'serviceEvaluation': 'Service Evaluation',
      'submitComplaint': 'Submit a Complaint',
      'personalHealthIdentity': 'Personal health identity',
      'infoUsedForYourCare': 'Information used for your care',
      'age': 'Age',
      'gender': 'Gender',
      'bloodType': 'Blood type',
      'mobile': 'Mobile',
      'verified': 'Verified',
      'preferences': 'Preferences',
      'preferencesSubtitle': 'Make Naraak work better for you',
      'accessibility': 'Accessibility',
      'appearance': 'Appearance',
      'lightMode': 'Light mode',
      'familyManagement': 'Family management',
      'manageLinkedMembers': 'Manage linked members',
      'feedbackSupport': 'Feedback & support',
      'weAreHereToHelp': 'We are here to help',
      'display': 'DISPLAY',
      'textSize': 'Text Size',
      'switchAccount': 'Switch Account',
      'organizeFamilyMembers': 'Organize Family Members',
      'notificationsSection': 'NOTIFICATIONS',
      'appointmentReminders': 'Appointment Reminders',
      'beforeUpcomingVisits': 'Get notified before upcoming visits',
      'requestStatusUpdates': 'Request Status Updates',
      'submittedRequestStatus': 'When a submitted request changes status',
      'promotionalMessages': 'Promotional Messages',
      'healthCampaigns': 'Health campaigns and PHC news',
      'appSettingsTitle': 'App Settings',
    },
    'ar': {
      'appName': 'نراك',
      'primaryHealthcarePortal': 'بوابة الرعاية الصحية الأولية',
      'signIn': 'تسجيل الدخول',
      'enterCprNumber': 'أدخل رقمك الشخصي للمتابعة',
      'cprNumber': 'رقم الهوية',
      'cprDigitsOnly': 'يجب أن يحتوي رقم الهوية على أرقام فقط',
      'cprTooShort': 'رقم الهوية قصير جدًا',
      'loginDemo': 'تسجيل الدخول عبر eKey (عرض توضيحي)',
      'home': 'الرئيسية',
      'homeTab': 'الرئيسية',
      'services': 'الخدمات',
      'servicesTab': 'الخدمات',
      'appointments': 'المواعيد',
      'appointmentsTab': 'المواعيد',
      'profile': 'الملف الشخصي',
      'profileTab': 'الملف الشخصي',
      'welcome': 'مرحباً بعودتك',
      'healthCenter': 'مركز الرعاية الصحية',
      'upcoming': 'الموعد القادم',
      'notifications': 'الإشعارات',
      'higherPriority': 'الوصول السريع',
      'moreServices': 'المزيد من الخدمات',
      'settings': 'الإعدادات',
      'darkMode': 'الوضع الداكن',
      'arabic': 'العربية',
      'english': 'English',
      'language': 'اللغة',
      'decreaseTextSize': 'تصغير حجم النص',
      'increaseTextSize': 'تكبير حجم النص',
      'welcomeHeadline': 'الرعاية الصحية الأولية، أقرب إليك',
      'welcomeSubtitle':
          'جميع خدمات الرعاية الصحية الأولية في مكان واحد. سريعة وسهلة وآمنة.',
      'fast': 'سريع',
      'secure': 'آمن',
      'easy': 'سهل',
      'loginWithEkey': 'تسجيل الدخول بالمفتاح الإلكتروني',
      'learnMoreNaraak': 'اعرف المزيد عن نراك',
      'naraakPrototypeDescription':
          'نراك منصة نموذجية للخدمات الإلكترونية الرقمية لمراكز الرعاية الصحية الأولية في البحرين.',
      'back': 'رجوع',
      'welcomeToNaraak': 'مرحباً بك في نراك',
      'useCprSecurely': 'استخدم رقمك الشخصي للمتابعة بأمان.',
      'ekeyAuthentication': 'المصادقة بالمفتاح الإلكتروني',
      'simulatedAccess': 'دخول تجريبي للنموذج الأولي',
      'cprNumberLabel': 'الرقم الشخصي',
      'enterNineDigitCpr': 'أدخل الرقم الشخصي المكون من 9 أرقام',
      'enterCprNumberValidation': 'أدخل رقمك الشخصي',
      'cprMustBeNineDigits': 'يجب أن يتكون الرقم الشخصي من 9 أرقام',
      'continueWithEkey': 'المتابعة بالمفتاح الإلكتروني',
      'completeYourProfile': 'أكمل ملفك الشخصي',
      'tellUsAboutYourself': 'أخبرنا عن نفسك',
      'profileSetupSubtitle':
          'بعض التفاصيل لتخصيص لوحة التحكم. تبقى هذه البيانات على جهازك خلال هذه الجلسة التجريبية فقط.',
      'cprFromLogin': 'الرقم الشخصي (من تسجيل الدخول)',
      'fullName': 'الاسم الكامل',
      'enterFullName': 'أدخل اسمك الكامل',
      'enterValidAge': 'أدخل عمراً صحيحاً',
      'mustBeFifteen': 'يجب أن يكون العمر 15 عاماً أو أكثر',
      'female': 'أنثى',
      'male': 'ذكر',
      'mobileNumber': 'رقم الهاتف المحمول',
      'enterMobileNumber': 'أدخل رقم هاتفك المحمول',
      'assignedHealthCenter': 'المركز الصحي المخصص',
      'saveAndContinue': 'حفظ ومتابعة',
      'hooraHealthCenter': 'مركز الحورة الصحي',
      'naimHealthCenter': 'مركز النعيم الصحي',
      'muharraqHealthCenter': 'مركز المحرق الصحي',
      'biladQadeemHealthCenter': 'مركز بلاد القديم الصحي',
      'yousifHealthCenter': 'مركز يوسف الصحي (سترة)',
      'dashboardLoadError': 'تعذر تحميل لوحة التحكم',
      'pleaseTryAgain': 'يرجى المحاولة مرة أخرى.',
      'tryAgain': 'إعادة المحاولة',
      'upcomingAppointment': 'الموعد القادم',
      'viewAllAppointments': 'عرض جميع المواعيد',
      'topServices': 'أبرز الخدمات',
      'viewAllServices': 'عرض جميع الخدمات',
      'webHeroTitle': 'الرعاية الصحية الأولية،\nأقرب إليك',
      'webHeroSubtitle':
          'جميع خدمات الرعاية الصحية الأولية في مكان واحد.\nسريعة وسهلة وآمنة.',
      'dashboardSearchHint': 'ابحث عن الخدمات والمراكز الصحية والمزيد...',
      'secureTrusted': 'آمن وموثوق',
      'allDayAccess': 'متاح على مدار الساعة',
      'forYourFamily': 'لك ولعائلتك',
      'betterHealthEveryday': 'صحة أفضل كل يوم',
      'noUpcomingAppointment': 'لا يوجد موعد قادم',
      'bookWhenReady': 'احجز موعداً عندما تكون مستعداً.',
      'generalPractitioner': 'طبيب عام',
      'type': 'النوع',
      'inCenter': 'في المركز',
      'viewDetails': 'عرض التفاصيل',
      'yourFamilyDoctor': 'طبيب العائلة',
      'notAssigned': 'غير معيّن',
      'familyMedicine': 'طب العائلة',
      'viewDoctor': 'عرض الطبيب',
      'bookingServiceSubtitle': 'موعد حضوري أو عن بُعد',
      'mammogramScreening': 'فحص الماموغرام',
      'mammogramSubtitle': 'الكشف المبكر ينقذ الحياة',
      'vaccinationRecords': 'سجلات التطعيم',
      'vaccinationSubtitle': 'عرض الشهادات وتنزيلها',
      'medicalReportsSubtitle': 'طلب التقارير وتنزيلها',
      'hajjCertificate': 'شهادة الحج الإلكترونية',
      'applyAndDownload': 'تقديم الطلب والتنزيل',
      'newbornSehatiCard': 'بطاقة صحتي لحديثي الولادة',
      'newbornSubtitle': 'تقديم طلب لمولودك',
      'updateAddress': 'تحديث العنوان',
      'updateAddressSubtitle': 'تحديث المركز الصحي المخصص',
      'healthFeeExemption': 'الإعفاء من الرسوم الصحية',
      'feeExemptionSubtitle': 'تقديم طلب إعفاء',
      'changeFamilyDoctor': 'تغيير طبيب العائلة',
      'changeDoctorSubtitle': 'اختر طبيب العائلة',
      'mobileUnitService': 'خدمة الوحدة المتنقلة',
      'mobileUnitSubtitle': 'الرعاية الصحية عند باب منزلك',
      'phcResearch': 'بحوث الرعاية الصحية الأولية',
      'phcResearchSubtitle': 'المشاريع والدراسات البحثية',
      'healthcareAtFingertips': 'الرعاية الصحية\nبين يديك',
      'appPromoDescription':
          'احجز المواعيد واطلع على سجلاتك وتابع الطلبات واستقبل التذكيرات وأدر رعايتك الصحية من أي مكان.',
      'openNaraakApp': 'فتح تطبيق نراك',
      'availablePrototypeApp': 'متاح كتطبيق نراك التجريبي',
      'healthTip': 'نصيحة صحية',
      'healthTipBody':
          'اشرب كمية كافية من الماء وتناول وجبات متوازنة واحصل على نوم كافٍ. العادات اليومية الصغيرة تقود إلى صحة أفضل.',
      'toggleDarkMode': 'تبديل الوضع الداكن',
      'readScreenAloud': 'قراءة الشاشة بصوت عالٍ',
      'screenReaderAnnouncement': 'تم تفعيل قارئ الشاشة لهذا العرض التجريبي.',
      'screenReaderDemo': 'تم الإعلان بواسطة قارئ الشاشة (تجريبي).',
      'logout': 'تسجيل الخروج',
      'externalApiTitle': 'يتطلب اتصالاً خارجياً',
      'externalApiMessage':
          'تتطلب هذه الخدمة واجهة API خارجية للعمل. الواجهة جاهزة، ولكن يجب ربط الخدمة لتفعيل الطلبات الفعلية.',
      'close': 'إغلاق',
      'startService': 'بدء الخدمة',
      'guest': 'زائر',
      'notSet': 'غير محدد',
      'cpr': 'الرقم الشخصي',
      'booking': 'حجز المواعيد',
      'medicalReports': 'التقارير الطبية والشهادات',
      'teleAppointment': 'تعليمات الموعد عن بُعد',
      'changeDoctor': 'تغيير طبيب العائلة',
      'addressUpdate': 'تحديث العنوان السكني',
      'vaccinations': 'سجل التطعيمات والشهادة',
      'hajj': 'شهادة الحج الإلكترونية',
      'feeExemption': 'بطاقة الإعفاء من الرسوم الصحية',
      'mobileUnit': 'طلب خدمة الوحدة المتنقلة',
      'mammogram': 'طلبات مواعيد فحص الثدي',
      'newborn': 'بطاقة صحتي لحديثي الولادة',
      'research': 'طلبات أبحاث الرعاية الأولية',
      'catAppointments': 'المواعيد والاستشارات',
      'catRecords': 'سجلاتي',
      'catAdmin': 'الخدمات الإدارية',
      'catResearch': 'طلبات الأبحاث',
      'allServices': 'جميع الخدمات',
      'yourCareTeam': 'فريق الرعاية الخاص بك',
      'yourAssignedFamilyDoctor': 'طبيب العائلة المعين لك',
      'nextAppointment': 'الموعد القادم',
      'yourUpcomingVisit': 'زيارتك القادمة',
      'popularServices': 'الخدمات الشائعة',
      'startWithWhatYouNeedToday': 'ابدأ بما تحتاجه اليوم',
      'viewingAs': 'يعرض كـ',
      'quickAccess': 'الوصول السريع',
      'commonServices': 'الخدمات الشائعة',
      'bookAppointment': 'حجز موعد',
      'medicalReportsQuick': 'التقارير الطبية',
      'vaccinationsQuick': 'التطعيمات',
      'allServicesQuick': 'جميع الخدمات',
      'noUpcomingAppointments': 'لا توجد مواعيد قادمة',
      'tapToScheduleNewVisit': 'اضغط لحجز زيارة جديدة',
      'pendingRequests': 'الطلبات المعلقة',
      'keepTrackOfApplications': 'تابع التطبيقات والتحديثات.',
      'noPendingRequests': 'لا توجد طلبات معلقة',
      'viewRequests': 'عرض الطلبات',
      'privacyMatters': 'خصوصيتك مهمة',
      'privacyDescription':
          'يحافظ نراك على معلوماتك الصحية بشكل آمن ويستخدمها فقط لتقديم الرعاية لك.',
      'privacySecurity': 'الخصوصية والأمان',
      'yourNaraakProfile': 'ملفك الشخصي في نراك',
      'profileSettingsTitle': 'الملف الشخصي والإعدادات',
      'profileSettingsSubtitle': 'إدارة هويتك والتفضيلات ووصول أفراد الأسرة.',
      'primaryMedicalTheme': 'السمة الطبية الأساسية',
      'signOut': 'تسجيل الخروج',
      'personalInfoMenu': 'المعلومات الشخصية وفصيلة الدم',
      'securityMenu': 'الخصوصية والأمان',
      'familyMenu': 'أفراد الأسرة والمعالين',
      'appSettingsMenu': 'إعدادات التطبيق',
      'helpSupportMenu': 'المساعدة والاستفسارات',
      'feedbackAndEvaluation': 'الملاحظات والتقييم',
      'serviceEvaluation': 'تقييم الخدمة',
      'submitComplaint': 'إرسال شكوى',
      'personalHealthIdentity': 'هوية الرعاية الصحية',
      'infoUsedForYourCare': 'المعلومات المستخدمة في رعايتك',
      'age': 'العمر',
      'gender': 'الجنس',
      'bloodType': 'فصيلة الدم',
      'mobile': 'الجوال',
      'verified': 'تم التحقق',
      'preferences': 'التفضيلات',
      'preferencesSubtitle': 'اجعل نراك يعمل بشكل أفضل لك',
      'accessibility': 'إمكانية الوصول',
      'appearance': 'المظهر',
      'lightMode': 'الوضع الفاتح',
      'familyManagement': 'إدارة الأسرة',
      'manageLinkedMembers': 'إدارة الأعضاء المرتبطين',
      'feedbackSupport': 'الملاحظات والدعم',
      'weAreHereToHelp': 'نحن هنا للمساعدة',
      'display': 'العرض',
      'textSize': 'حجم النص',
      'switchAccount': 'تبديل الحساب',
      'organizeFamilyMembers': 'تنظيم أفراد الأسرة',
      'notificationsSection': 'الإشعارات',
      'appointmentReminders': 'تذكيرات المواعيد',
      'beforeUpcomingVisits': 'تلقي تنبيهات قبل الزيارات القادمة',
      'requestStatusUpdates': 'تحديثات حالة الطلب',
      'submittedRequestStatus': 'عند تغيير حالة الطلب المقدم',
      'promotionalMessages': 'الرسائل الترويجية',
      'healthCampaigns': 'حملات صحية وأخبار الرعاية الصحية',
      'appSettingsTitle': 'إعدادات التطبيق',
    },
  };

  static const _arabicRaw = <String, String>{
    'Book Appointment': 'حجز موعد',
    'Care that fits your day': 'رعاية تناسب يومك',
    'Choose a video consultation or an in-center visit. Tele-appointment remains part of Book Appointment.':
        'اختر استشارة مرئية أو زيارة حضورية. يظل الموعد عن بُعد جزءاً من خدمة حجز الموعد.',
    'Choose appointment type': 'اختر نوع الموعد',
    'Tele-appointment': 'موعد عن بُعد',
    'Video call with your doctor from a private place.':
        'مكالمة مرئية مع طبيبك من مكان خاص.',
    'In-center appointment': 'موعد حضوري',
    'Visit your health center and meet the care team.':
        'زر مركزك الصحي وقابل فريق الرعاية.',
    'Mammogram Screening': 'فحص الماموغرام',
    'Early detection saves lives': 'الكشف المبكر ينقذ الحياة',
    'Check your eligibility and book your screening.':
        'تحقق من أهليتك واحجز موعد الفحص.',
    'What would you like to do?': 'ماذا تريد أن تفعل؟',
    'Check eligibility': 'التحقق من الأهلية',
    'See if you qualify based on age and screening history.':
        'تحقق من أهليتك بناءً على العمر وسجل الفحوصات.',
    'Book screening': 'حجز الفحص',
    'Start a new screening request.': 'ابدأ طلب فحص جديداً.',
    'My screenings': 'فحوصاتي',
    'Track the status of your submitted requests.': 'تابع حالة طلباتك المقدمة.',
    'Vaccination Records': 'سجلات التطعيم',
    'Your vaccination history': 'سجل تطعيماتك',
    'Review your recorded vaccinations, download a certificate, or report a missing entry.':
        'راجع تطعيماتك المسجلة أو نزّل شهادة أو أبلغ عن سجل مفقود.',
    'View or download records': 'عرض السجلات أو تنزيلها',
    'Open your vaccination history and certificate.':
        'افتح سجل التطعيم وشهادته.',
    'Report a missing vaccination': 'الإبلاغ عن تطعيم مفقود',
    'Submit a request from within Vaccination Records.':
        'قدّم طلباً من داخل سجلات التطعيم.',
    'Medical Reports': 'التقارير الطبية',
    'Reports in one secure place': 'تقاريرك في مكان آمن واحد',
    'View available PHC reports or request a report from a previous visit.':
        'اعرض تقارير الرعاية الصحية الأولية أو اطلب تقريراً عن زيارة سابقة.',
    'Choose an option': 'اختر أحد الخيارات',
    'View my reports': 'عرض تقاريري',
    'See and download your available PHC reports.':
        'اعرض تقاريرك المتاحة ونزّلها.',
    'Request a report': 'طلب تقرير',
    'Submit a medical report request for a recent visit.':
        'قدّم طلب تقرير طبي عن زيارة حديثة.',
    'Electronic Hajj Certificate': 'شهادة الحج الإلكترونية',
    'Download your Hajj health certificate once your pre-travel visit is on file.':
        'نزّل شهادة الحج الصحية بعد تسجيل زيارتك السابقة للسفر.',
    'Newborn Sehati Card': 'بطاقة صحتي لحديثي الولادة',
    'Register your newborn and request their health card.':
        'سجّل مولودك واطلب بطاقته الصحية.',
    'Update Address': 'تحديث العنوان',
    'Update Residential Address': 'تحديث عنوان السكن',
    'Update your block and see your newly assigned health center.':
        'حدّث رقم المجمع واعرض مركزك الصحي الجديد.',
    'Fee Exemption Card': 'بطاقة الإعفاء من الرسوم',
    'Health Fee Exemption Card': 'بطاقة الإعفاء من الرسوم الصحية',
    'Apply for health fee exemption based on your entitlement.':
        'قدّم طلب إعفاء من الرسوم الصحية حسب استحقاقك.',
    'Change Family Doctor': 'تغيير طبيب العائلة',
    'Health center not found': 'لم يتم العثور على المركز الصحي',
    'Mobile Unit Service': 'خدمة الوحدة المتنقلة',
    'Healthcare at your doorstep': 'الرعاية الصحية عند باب منزلك',
    'Request a primary care visit at home for you or a linked family member.':
        'اطلب زيارة رعاية أولية منزلية لك أو لأحد أفراد عائلتك المرتبطين.',
    'New request': 'طلب جديد',
    'Ask for a primary care visit at home.': 'اطلب زيارة رعاية أولية منزلية.',
    'My requests': 'طلباتي',
    'Track the status of your visit requests.': 'تابع حالة طلبات الزيارة.',
    'Visit schedule': 'جدول الزيارات',
    'See your next confirmed visit.': 'اعرض زيارتك المؤكدة القادمة.',
    'Research Application': 'طلب بحث',
    'PHC Research Application': 'طلب بحث للرعاية الصحية الأولية',
    'Apply to conduct research studies at PHC centers.':
        'قدّم طلباً لإجراء دراسات بحثية في مراكز الرعاية الصحية الأولية.',
    'New application': 'طلب جديد',
    'Submit a research application to PHC.':
        'قدّم طلب بحث إلى الرعاية الصحية الأولية.',
    'My applications': 'طلباتي البحثية',
    'Track the status of your submitted applications.':
        'تابع حالة طلباتك البحثية المقدمة.',
    'Application guidelines': 'إرشادات التقديم',
    'Read what is required before you apply.':
        'اطلع على المتطلبات قبل التقديم.',
    'Services': 'الخدمات',
    'NARAAK SERVICES': 'خدمات نراك',
    'All your health services in one place.':
        'جميع خدماتك الصحية في مكان واحد.',
    'Search for a service...': 'ابحث عن خدمة...',
    'YOUR HEALTH, YOUR WAY': 'صحتك، بطريقتك',
    'Simple access to primary care.': 'وصول سهل إلى الرعاية الأولية.',
    'Book, request and manage services without visiting the center for every step.':
        'احجز واطلب وأدر الخدمات دون زيارة المركز في كل خطوة.',
    'Book and manage your appointments.': 'احجز مواعيدك وأدرها.',
    'Access your medical records and certificates.':
        'اطلع على سجلاتك وشهاداتك الطبية.',
    'Manage your requests and official services.':
        'أدر طلباتك وخدماتك الرسمية.',
    'Apply for research and studies.': 'قدّم طلبات البحوث والدراسات.',
    'Appointments': 'المواعيد',
    'YOUR CARE': 'رعايتك',
    'Manage upcoming visits and review your appointment history.':
        'أدر زياراتك القادمة وراجع سجل مواعيدك.',
    'Upcoming': 'القادمة',
    'Past': 'السابقة',
    'Tele-appointments': 'المواعيد عن بُعد',
    'In-center': 'حضوري',
    'Doctor': 'الطبيب',
    'Clinic': 'العيادة',
    'Health Center': 'المركز الصحي',
    'Date & Time': 'التاريخ والوقت',
    'Type': 'النوع',
    'Status': 'الحالة',
    'Actions': 'الإجراءات',
    'Confirmed': 'مؤكد',
    'Join': 'انضمام',
    'Cancel': 'إلغاء',
    'Profile & settings': 'الملف الشخصي والإعدادات',
    'YOUR NARAAK PROFILE': 'ملفك في نراك',
    'Manage your identity, preferences and family access.':
        'أدر هويتك وتفضيلاتك ووصول أفراد العائلة.',
    'PRIMARY MEDICAL THEME': 'السمة الطبية الأساسية',
    'Edit personal information': 'تعديل المعلومات الشخصية',
    'Preferences': 'التفضيلات',
    'Make Naraak work better for you': 'اجعل نراك يعمل بشكل أفضل لك',
    'Accessibility': 'إمكانية الوصول',
    'Appearance': 'المظهر',
    'Family management': 'إدارة العائلة',
    'Privacy & security': 'الخصوصية والأمان',
    'Feedback & support': 'الملاحظات والدعم',
    'Reference Number': 'الرقم المرجعي',
    'Requester CPR': 'الرقم الشخصي لمقدم الطلب',
    'Current Block Number': 'رقم المجمع الحالي',
    'New Block Number *': 'رقم المجمع الجديد *',
    'Select New Block': 'اختر المجمع الجديد',
    'Confirm Address Update': 'تأكيد تحديث العنوان',
    'Address Updated': 'تم تحديث العنوان',
    'Back to Services': 'العودة إلى الخدمات',
    'Request Submitted': 'تم تقديم الطلب',
    'Registry match found': 'تم العثور على سجل مطابق',
    'Continue': 'متابعة',
    'Newborn information': 'معلومات المولود',
    'Confirm the family details for this registration.':
        'أكد بيانات العائلة لهذا التسجيل.',
    'Newborn CPR': 'الرقم الشخصي للمولود',
    'Father CPR': 'الرقم الشخصي للأب',
    'Mother CPR': 'الرقم الشخصي للأم',
    'Contact': 'بيانات الاتصال',
    'Notes (optional)': 'ملاحظات (اختياري)',
    'Required documents': 'المستندات المطلوبة',
    'Attach the hospital birth notification if available.':
        'أرفق إشعار الولادة من المستشفى إن توفر.',
    'Birth Notification': 'إشعار الولادة',
    'Review your request': 'راجع طلبك',
    'Confirm the details before submitting.': 'أكد البيانات قبل التقديم.',
    'Block': 'المجمع',
    'Notes': 'الملاحظات',
    'Document': 'المستند',
    'Not attached': 'غير مرفق',
    'Back': 'رجوع',
    'Submit': 'إرسال',
    'Error Loading Service': 'حدث خطأ أثناء تحميل الخدمة',
    'No download available yet': 'لا يتوفر تنزيل حتى الآن',
    'I\'ve Requested It From My Doctor': 'طلبتها من طبيبي',
    'Find Nearest Health Center': 'العثور على أقرب مركز صحي',
    'Not available in this demo.': 'غير متاح في هذا العرض التجريبي.',
    'CURRENT REQUEST STATUS': 'حالة الطلب الحالية',
    'APPLICATION PROGRESS': 'تقدم الطلب',
    'Find my health centre': 'العثور على مركزي الصحي',
    'Download certificate': 'تنزيل الشهادة',
    'Application Submitted': 'تم تقديم الطلب',
    'View Pending Requests': 'عرض الطلبات المعلقة',
    'Could not check eligibility': 'تعذر التحقق من الأهلية',
    'You already have a pending request': 'لديك طلب معلق بالفعل',
    'Before you begin, please prepare:': 'قبل البدء، يرجى تجهيز:',
    'Start Application': 'بدء الطلب',
    'Gender': 'الجنس',
    'Nationality': 'الجنسية',
    'Request Type': 'نوع الطلب',
    'Marital Status': 'الحالة الاجتماعية',
    'Spouse Nationality': 'جنسية الزوج أو الزوجة',
    'Contact Number': 'رقم الاتصال',
    'Email': 'البريد الإلكتروني',
    'Case Description': 'وصف الحالة',
    'Next — Upload Documents': 'التالي — رفع المستندات',
    'Please upload CPR Copy to proceed.':
        'يرجى رفع نسخة من البطاقة الشخصية للمتابعة.',
    'Patient CPR': 'الرقم الشخصي للمريض',
    'Patient Name': 'اسم المريض',
    'Current Health Center': 'المركز الصحي الحالي',
    'Current Family Doctor': 'طبيب العائلة الحالي',
    'Requested Family Doctor *': 'طبيب العائلة المطلوب *',
    'No other doctors available': 'لا يوجد أطباء آخرون متاحون',
    'Reason for Request *': 'سبب الطلب *',
  };

  String raw(String value) =>
      locale.languageCode == 'ar' ? (_arabicRaw[value] ?? value) : value;
  String text(String key) =>
      _values[locale.languageCode]?[key] ?? _values['en']![key] ?? key;

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
