import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  const AppLocalizations(this.locale);

  static const supportedLocales = [Locale('en'), Locale('ar')];

  static const _values = <String, Map<String, String>>{
    'en': {
      'appName': 'Naraak',
      'primaryHealthcarePortal': 'Primary Healthcare Portal',
      'signIn': 'Sign in',
      'enterCprNumber': 'Enter your CPR number to continue',
      'cprNumber': 'CPR NUMBER',
      'cprDigitsOnly': 'CPR number must contain digits only',
      'cprTooShort': 'CPR number looks too short',
      'loginDemo': 'Log in with eKey (Demo)',
      'home': 'Home',
      'homeTab': 'Home',
      'services': 'Services',
      'servicesTab': 'Services',
      'appointments': 'Appointments',
      'appointmentsTab': 'Appointments',
      'profile': 'Profile',
      'profileTab': 'Profile',
      'welcome': 'Welcome back',
      'healthCenter': 'My health center',
      'upcoming': 'Upcoming appointment',
      'notifications': 'Notifications',
      'higherPriority': 'Quick access',
      'moreServices': 'More services',
      'settings': 'Settings',
      'darkMode': 'Dark mode',
      'arabic': 'العربية',
      'english': 'English',
      'logout': 'Log out',
      'externalApiTitle': 'External API required',
      'externalApiMessage':
          'This service requires an external API to operate. The interface is ready, but connect the service API to enable live requests.',
      'close': 'Close',
      'startService': 'Start Service',
      'guest': 'Guest',
      'notSet': 'Not set',
      'cpr': 'CPR',
      'booking': 'Booking Appointments',
      'medicalReports': 'Medical Reports & Certificates',
      'teleAppointment': 'Tele-Appointment Instructions',
      'changeDoctor': 'Change Family Doctor',
      'addressUpdate': 'Update Residential Address',
      'vaccinations': 'Vaccination Records & Certificate',
      'hajj': 'Electronic Hajj Certificate',
      'feeExemption': 'Health Fee Exemption Card',
      'mobileUnit': 'Request Mobile Unit Service',
      'mammogram': 'Mammogram Appointment Requests',
      'newborn': 'Sehati Card for Newborns',
      'research': 'PHC Research Applications',
      'catAppointments': 'Appointments & Consultation',
      'catRecords': 'My Records',
      'catAdmin': 'Administrative Services',
      'catResearch': 'Research Applications',
      'allServices': 'All Services',
      'yourCareTeam': 'Your care team',
      'yourAssignedFamilyDoctor': 'Your assigned family doctor',
      'nextAppointment': 'Next appointment',
      'yourUpcomingVisit': 'Your upcoming visit',
      'popularServices': 'Popular services',
      'startWithWhatYouNeedToday': 'Start with what you need today',
      'viewingAs': 'Viewing as',
      'quickAccess': 'Quick access',
      'commonServices': 'Common services',
      'bookAppointment': 'Book appointment',
      'medicalReportsQuick': 'Medical reports',
      'vaccinationsQuick': 'Vaccinations',
      'allServicesQuick': 'All services',
      'noUpcomingAppointments': 'No upcoming appointments',
      'tapToScheduleNewVisit': 'Tap to schedule a new visit',
      'pendingRequests': 'Pending requests',
      'keepTrackOfApplications': 'Keep track of applications and updates.',
      'noPendingRequests': 'No pending requests',
      'viewRequests': 'View requests',
      'privacyMatters': 'Your privacy matters',
      'privacyDescription':
          'Naraak keeps your health information safe and only uses it to provide your care.',
      'privacySecurity': 'Privacy & security',
      'yourNaraakProfile': 'YOUR NARAAK PROFILE',
      'profileSettingsTitle': 'Profile & settings',
      'profileSettingsSubtitle':
          'Manage your identity, preferences and family access.',
      'primaryMedicalTheme': 'PRIMARY MEDICAL THEME',
      'signOut': 'Sign Out',
      'personalInfoMenu': 'Personal Info & Blood Type',
      'securityMenu': 'Privacy & Security',
      'familyMenu': 'Family Members & Dependents',
      'appSettingsMenu': 'App Settings',
      'helpSupportMenu': 'Help & User Inquiries',
      'feedbackAndEvaluation': 'FEEDBACK & EVALUATION',
      'serviceEvaluation': 'Service Evaluation',
      'submitComplaint': 'Submit a Complaint',
      'personalHealthIdentity': 'Personal health identity',
      'infoUsedForYourCare': 'Information used for your care',
      'age': 'Age',
      'gender': 'Gender',
      'bloodType': 'Blood type',
      'mobile': 'Mobile',
      'verified': 'Verified',
      'preferences': 'Preferences',
      'preferencesSubtitle': 'Make Naraak work better for you',
      'accessibility': 'Accessibility',
      'appearance': 'Appearance',
      'lightMode': 'Light mode',
      'familyManagement': 'Family management',
      'manageLinkedMembers': 'Manage linked members',
      'feedbackSupport': 'Feedback & support',
      'weAreHereToHelp': 'We are here to help',
      'display': 'DISPLAY',
      'textSize': 'Text Size',
      'switchAccount': 'Switch Account',
      'organizeFamilyMembers': 'Organize Family Members',
      'notificationsSection': 'NOTIFICATIONS',
      'appointmentReminders': 'Appointment Reminders',
      'beforeUpcomingVisits': 'Get notified before upcoming visits',
      'requestStatusUpdates': 'Request Status Updates',
      'submittedRequestStatus': 'When a submitted request changes status',
      'promotionalMessages': 'Promotional Messages',
      'healthCampaigns': 'Health campaigns and PHC news',
      'appSettingsTitle': 'App Settings',
    },
    'ar': {
      'appName': 'نراك',
      'primaryHealthcarePortal': 'بوابة الرعاية الصحية الأولية',
      'signIn': 'تسجيل الدخول',
      'enterCprNumber': 'أدخل رقمك الشخصي للمتابعة',
      'cprNumber': 'رقم الهوية',
      'cprDigitsOnly': 'يجب أن يحتوي رقم الهوية على أرقام فقط',
      'cprTooShort': 'رقم الهوية قصير جدًا',
      'loginDemo': 'تسجيل الدخول عبر eKey (عرض توضيحي)',
      'home': 'الرئيسية',
      'homeTab': 'الرئيسية',
      'services': 'الخدمات',
      'servicesTab': 'الخدمات',
      'appointments': 'المواعيد',
      'appointmentsTab': 'المواعيد',
      'profile': 'الملف الشخصي',
      'profileTab': 'الملف الشخصي',
      'welcome': 'مرحباً بعودتك',
      'healthCenter': 'مركز الرعاية الصحية',
      'upcoming': 'الموعد القادم',
      'notifications': 'الإشعارات',
      'higherPriority': 'الوصول السريع',
      'moreServices': 'المزيد من الخدمات',
      'settings': 'الإعدادات',
      'darkMode': 'الوضع الداكن',
      'arabic': 'العربية',
      'english': 'English',
      'logout': 'تسجيل الخروج',
      'externalApiTitle': 'يتطلب اتصالاً خارجياً',
      'externalApiMessage':
          'تتطلب هذه الخدمة واجهة API خارجية للعمل. الواجهة جاهزة، ولكن يجب ربط الخدمة لتفعيل الطلبات الفعلية.',
      'close': 'إغلاق',
      'startService': 'بدء الخدمة',
      'guest': 'زائر',
      'notSet': 'غير محدد',
      'cpr': 'الرقم الشخصي',
      'booking': 'حجز المواعيد',
      'medicalReports': 'التقارير الطبية والشهادات',
      'teleAppointment': 'تعليمات الموعد عن بُعد',
      'changeDoctor': 'تغيير طبيب العائلة',
      'addressUpdate': 'تحديث العنوان السكني',
      'vaccinations': 'سجل التطعيمات والشهادة',
      'hajj': 'شهادة الحج الإلكترونية',
      'feeExemption': 'بطاقة الإعفاء من الرسوم الصحية',
      'mobileUnit': 'طلب خدمة الوحدة المتنقلة',
      'mammogram': 'طلبات مواعيد فحص الثدي',
      'newborn': 'بطاقة صحتي لحديثي الولادة',
      'research': 'طلبات أبحاث الرعاية الأولية',
      'catAppointments': 'المواعيد والاستشارات',
      'catRecords': 'سجلاتي',
      'catAdmin': 'الخدمات الإدارية',
      'catResearch': 'طلبات الأبحاث',
      'allServices': 'جميع الخدمات',
      'yourCareTeam': 'فريق الرعاية الخاص بك',
      'yourAssignedFamilyDoctor': 'طبيب العائلة المعين لك',
      'nextAppointment': 'الموعد القادم',
      'yourUpcomingVisit': 'زيارتك القادمة',
      'popularServices': 'الخدمات الشائعة',
      'startWithWhatYouNeedToday': 'ابدأ بما تحتاجه اليوم',
      'viewingAs': 'يعرض كـ',
      'quickAccess': 'الوصول السريع',
      'commonServices': 'الخدمات الشائعة',
      'bookAppointment': 'حجز موعد',
      'medicalReportsQuick': 'التقارير الطبية',
      'vaccinationsQuick': 'التطعيمات',
      'allServicesQuick': 'جميع الخدمات',
      'noUpcomingAppointments': 'لا توجد مواعيد قادمة',
      'tapToScheduleNewVisit': 'اضغط لحجز زيارة جديدة',
      'pendingRequests': 'الطلبات المعلقة',
      'keepTrackOfApplications': 'تابع التطبيقات والتحديثات.',
      'noPendingRequests': 'لا توجد طلبات معلقة',
      'viewRequests': 'عرض الطلبات',
      'privacyMatters': 'خصوصيتك مهمة',
      'privacyDescription':
          'يحافظ نراك على معلوماتك الصحية بشكل آمن ويستخدمها فقط لتقديم الرعاية لك.',
      'privacySecurity': 'الخصوصية والأمان',
      'yourNaraakProfile': 'ملفك الشخصي في نراك',
      'profileSettingsTitle': 'الملف الشخصي والإعدادات',
      'profileSettingsSubtitle': 'إدارة هويتك والتفضيلات ووصول أفراد الأسرة.',
      'primaryMedicalTheme': 'السمة الطبية الأساسية',
      'signOut': 'تسجيل الخروج',
      'personalInfoMenu': 'المعلومات الشخصية وفصيلة الدم',
      'securityMenu': 'الخصوصية والأمان',
      'familyMenu': 'أفراد الأسرة والمعالين',
      'appSettingsMenu': 'إعدادات التطبيق',
      'helpSupportMenu': 'المساعدة والاستفسارات',
      'feedbackAndEvaluation': 'الملاحظات والتقييم',
      'serviceEvaluation': 'تقييم الخدمة',
      'submitComplaint': 'إرسال شكوى',
      'personalHealthIdentity': 'هوية الرعاية الصحية',
      'infoUsedForYourCare': 'المعلومات المستخدمة في رعايتك',
      'age': 'العمر',
      'gender': 'الجنس',
      'bloodType': 'فصيلة الدم',
      'mobile': 'الجوال',
      'verified': 'تم التحقق',
      'preferences': 'التفضيلات',
      'preferencesSubtitle': 'اجعل نراك يعمل بشكل أفضل لك',
      'accessibility': 'إمكانية الوصول',
      'appearance': 'المظهر',
      'lightMode': 'الوضع الفاتح',
      'familyManagement': 'إدارة الأسرة',
      'manageLinkedMembers': 'إدارة الأعضاء المرتبطين',
      'feedbackSupport': 'الملاحظات والدعم',
      'weAreHereToHelp': 'نحن هنا للمساعدة',
      'display': 'العرض',
      'textSize': 'حجم النص',
      'switchAccount': 'تبديل الحساب',
      'organizeFamilyMembers': 'تنظيم أفراد الأسرة',
      'notificationsSection': 'الإشعارات',
      'appointmentReminders': 'تذكيرات المواعيد',
      'beforeUpcomingVisits': 'تلقي تنبيهات قبل الزيارات القادمة',
      'requestStatusUpdates': 'تحديثات حالة الطلب',
      'submittedRequestStatus': 'عند تغيير حالة الطلب المقدم',
      'promotionalMessages': 'الرسائل الترويجية',
      'healthCampaigns': 'حملات صحية وأخبار الرعاية الصحية',
      'appSettingsTitle': 'إعدادات التطبيق',
    },
  };

  String text(String key) =>
      _values[locale.languageCode]?[key] ?? _values['en']![key] ?? key;

  static AppLocalizations of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations)!;
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
